[package]
name = "dnsguide"
version = "0.1.0"
authors = ["Emil Hernvall <emil@c0la.se>"]

build = "tango-build.rs"

[build-dependencies.tango]
git = "https://github.com/pnkfelix/tango"

[lib]
name = "lib"
